/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:062d1889-d58a-43da-be37-9602b69a0837",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_XeR0Er33J",
    "aws_user_pools_web_client_id": "5d2t9srev7laauapngckei6i38",
    "oauth": {}
};


export default awsmobile;
