export const subjects = [
    {subject: "Arts", color: "#351431"},
    {subject: "Biology", color: "#775253"},
    {subject: "Chemistry", color: "#BDC696"}, 
    {subject: "Computer Science", color: "#D1D3C4"},
    {subject: "English", color: "#DFE0DC"},
    {subject: "French", color: "#D8A7CA"},
    {subject: "Geography", color: "#C7B8EA"}, 
    {subject: "German", color: "#447604"},
    {subject: "History", color: "#47624F"},
    {subject: "Maths", color: "#42CAFD"}, 
    {subject: "Music", color: "#1D4E89"},
    {subject: "Physical Education", color: "#FCFC62"},
    {subject: "Physics", color: "#F72585"},
    {subject: "Religion/Ethics", color: "#BFCDE0"}, 
    {subject: "Spanish", color: "#72A98F"},
]
